pipeline:
  name: VibePad-plus-plus
  identifier: VibePadplusplus
  projectIdentifier: NMcCarthy_Sandbox
  orgIdentifier: sandbox
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: jedicraftGitHub
        repoName: vibepad-plus-plus
        build: <+input>
  stages:
    - stage:
        name: Build and Test
        identifier: Build_and_Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  spec:
                    connectorRef: account.DockerHub
                    image: node:20-alpine
                    shell: Sh
                    command: |-
                      node --version
                      npm --version
                      npm install
              - step:
                  type: Run
                  name: Lint
                  identifier: Lint
                  spec:
                    connectorRef: DockerHub
                    image: node:20-alpine
                    shell: Sh
                    command: npm run lint
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    connectorRef: DockerHub
                    image: node:20-alpine
                    shell: Sh
                    command: npm run build
              - step:
                  type: Run
                  name: Verify Build Output
                  identifier: Verify_Build_Output
                  spec:
                    connectorRef: DockerHub
                    image: node:20-alpine
                    shell: Sh
                    command: |-
                      echo "=== Build Output ==="
                      ls -la dist/
                      echo "=== Index HTML ==="
                      head -20 dist/index.html
